excluded:
  - .build

opt_in_rules:
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - first_where
  - operator_usage_whitespace
  - sorted_imports

identifier_name:
  excluded:
    - id
    - url

line_length:
  ignores_urls: true

attributes:
  always_on_same_line:
    - "@Environment"
    - "@AppStorage"


cyclomatic_complexity:
  ignores_case_statements: true
