name: CI App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "ci-app-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build App
        run: xcodebuild build -scheme SwiftLeeds -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
