name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "ci-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build-for-testing -scheme SwiftLeeds -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
      
      - name: Test
        run: xcodebuild test-without-building -scheme SwiftLeeds -testPlan SwiftLeeds -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
  